# Generated by Django 2.2.5 on 2019-10-07 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_read', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_img',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_img', to=settings.AUTH_USER_MODEL),
        ),
    ]
