# Generated by Django 2.2.5 on 2019-11-16 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prescription_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediName', models.CharField(max_length=255)),
                ('insuranceCode', models.CharField(max_length=15)),
                ('img_url', models.CharField(default='', max_length=500)),
                ('entp', models.CharField(default='', max_length=500)),
                ('class_name', models.CharField(default='', max_length=500)),
                ('dosage', models.CharField(default='', max_length=500)),
                ('caution', models.CharField(default='', max_length=500)),
                ('rgstrDate', models.DateTimeField(auto_now_add=True)),
                ('linkPrescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_disease', to='prescription_manage.Prescription')),
            ],
        ),
    ]
