# Generated by Django 2.2.5 on 2019-10-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disease_manage', '0002_auto_20191002_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediName', models.CharField(max_length=255)),
                ('insuranceCode', models.CharField(max_length=15)),
                ('rgstrDate', models.DateTimeField(auto_now_add=True)),
                ('relatedDisease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_disease', to='disease_manage.Disease')),
            ],
        ),
    ]
