# Generated by Django 2.2.5 on 2019-10-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='img_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
