# Generated by Django 2.2.6 on 2019-11-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_manage', '0002_medicine_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='class_name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='medicine',
            name='entp',
            field=models.CharField(default='', max_length=500),
        ),
    ]
