# Generated by Django 2.2.6 on 2019-11-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_manage', '0003_auto_20191116_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='caution',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(default='', max_length=500),
        ),
    ]
