# Generated by Django 2.2.5 on 2019-10-03 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='linkPrescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_disease', to='prescription_manage.Prescription'),
        ),
    ]
