# Generated by Django 2.2.5 on 2019-10-02 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disease_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='ownUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
